Не могу разобраться, выбивает "Caused by: java.lang.NoSuchMethodError: net.minecraft.util.ResourceLocation.getResourcePath()Ljava/lang/String;" из-за галактика, нужна хелпа, не понимаю как написать dependencies в @Mod